# 從 Vibe Coding 到 Python：建立與探索大學生學習資料

以下教材可直接複製到 Google Colab 或 Jupyter Notebook 中使用。每個 Mission 依序包含：

* Knowledge Point：本單元要學的概念。
* Markdown Cell：給學生閱讀的簡短說明。
* Code Cell：可以直接執行的程式（已加入繁體中文註解）。
* 執行前預測：請先猜測執行結果。
* Try It：修改指定的數值、文字或參數後重新執行。
* Verification：檢查結果是否合理。
* Explain-back：用自己話解釋該段程式的輸入、處理與輸出。
注意：所有程式區塊均可逐段執行，建議依照順序從上到下走完全部 Mission，最後完成 最終整合任務 與 最終學習檢核。

# Mission 1：執行第一段 Python 程式

Knowledge Point

* 程式碼放在「程式儲存格」中，會由上往下依序執行。
* print() 用來在螢幕上顯示文字或變數的值。
* 字串用單引號 ' 或雙引號 " 包起來。

Markdown Cell

這是你的第一行 Python 程式。我們先定義一個變數 course_name，再用 print() 把歡迎訊息顯示出來。

In [9]:
# 課程名稱（字串）
course_name = "Python與資料科學"

# 顯示歡迎訊息
print("歡迎來到", course_name)

歡迎來到 Python與資料科學

執行前預測

螢幕會顯示什麼文字？

Try It

將 course_name 改成你自己的課程名稱（例如 "程式設計入門"），然後重新執行此格。

Verification

輸出是否如你所預期？如果看不到預期的文字，請檢查是否有打錯字或漏掉引號。

Explain-back

用你的話說明：這段程式到底做了哪兩件事？

# Mission 2：變數與資料型態

Knowledge Point

* 變數是用來暫存資料的命名空間，= 是「指定」運算子，不是數學上的等號。
* 常見型態：int（整數）、float（浮點數）、str（字串）、bool（布林值）。
* type() 可以查看變數所儲存的資料型態。

Markdown Cell

我們將建立四種不同型態的變數，代表班級的人數、平均睡眠時數、課程名稱以及是否有缺失值的旗標。

In [8]:
# 班級學生人數（整數）
student_count = 60
# 平均睡眠時數（浮點數）
average_sleep_hours = 6.7
# 課程名稱（字串）
course_name = "Python與資料科學"
# 是否存在缺失值的旗標（布林值）
has_missing_value = True

# 檢查每個變數的型態
print("student_count 的型態:", type(student_count))
print("average_sleep_hours 的型態:", type(average_sleep_hours))
print("course_name 的型態:", type(course_name))
print("has_missing_value 的型態:", type(has_missing_value))

student_count 的型態: <class 'int'>
average_sleep_hours 的型態: <class 'float'>
course_name 的型態: <class 'str'>
has_missing_value 的型態: <class 'bool'>

執行前預測

每一行 print 會顯示什麼內容？（例如 student_count 的型態: <class 'int'>）

Try It

修改 average_sleep_hours 為 7.2，再執行一次，觀察型態是否改變。

Verification

型態印出來是否符合你的預期？如果看到 <class 'float'> 表示仍是浮點數。

Explain-back

用你自己話解釋：= 在程式中代表什麼？為什麼我們需要 type()？

# Mission 3：串列、字典與索引

Knowledge Point

* list（串列）用方括號 [ ] 裝多個項目，索引從 0 開始。
* dict（字典）用大括號 { } 以「鍵：值」形式儲存資料，可透過鍵快速取值。
* len() 取得串列長度。
* for 迴圈可逐項處理串列中的每個元素。

Markdown Cell

先建立一個科系串列，示範如何取第一個元素、計算長度以及用迴圈印出每個科系。  
再建立一個簡單的學生字典，示範如何透過鍵取得科系與成績。

In [3]:
# 科系串列（list）
departments = ["資訊管理", "企業管理", "金融管理"]

# 顯示完整串列
print("完整科系串列:", departments)

# 取得第一個元素（索引 0）
print("第一個科系:", departments[0])

# 串列長度
print("科系數量:", len(departments))

# 用 for 迴圈依序印出每個科系
for dept in departments:
    print("科系：", dept)

# 簡單的學生字典（dict）
sample_student = {
    "student_id": 1,
    "department": "資訊管理",
    "sleep_hours": 7.0,
    "quiz_score": 82
}

# 透過鍵取得科系與成績
print("學生的科系:", sample_student["department"])
print("學生的 quiz_score:", sample_student["quiz_score"])

完整科系串列: ['資訊管理', '企業管理', '金融管理']
第一個科系: 資訊管理
科系數量: 3
科系： 資訊管理
科系： 企業管理
科系： 金融管理
學生的科系: 資訊管理
學生的 quiz_score: 82

執行前預測

先猜：departments[0] 會是什麼？len(departments) 會是多少？for 迴圈會印出幾行？字典取值會得到什麼？

Try It

將 departments 加入一個新科系（例如 "統計學"），再執行一次，觀察長度與迴圈輸出的變化。

Verification

新增的科系是否正確出現在串列中？長度是否加 1？字典的取值是否仍正常？

Explain-back

用你的話說明：串列與字典在取資料時的主要差別是什麼？

# Mission 4：算術運算與成績公式

Knowledge Point

* 基本算術運算子：+（加）、-（減）、*（乘）、/（除）。
* 可以先分步驟計算各項影響，最後再加總，讓程式更易閱讀。
* 此處的公式僅為示例，並不代表真實因果關係。

Markdown Cell

我們以一位假想學生的讀書時數、睡眠時數、螢幕使用時數與出席率，逐步計算模擬的小考成績。

In [7]:
# 假想學生的基本資料
study_hours = 2.5          # 讀書時數（小時）
sleep_hours = 7.0          # 睡眠時數（小時）
screen_time_hours = 4.0    # 螢幕使用時數（小時）
attendance_rate = 90       # 出席率（%）

# 分別計算各項對成績的影響
base_score = 50
study_effect = 3 * study_hours
sleep_effect = 2 * sleep_hours
screen_effect = -1.2 * screen_time_hours   # 負數代表扣分
attendance_effect = 0.15 * attendance_rate

# 加總得到未加隨機誤差的成績
quiz_score_raw = base_score + study_effect + sleep_effect + screen_effect + attendance_effect

print("基礎分數:", base_score)
print("讀書時數影響:", study_effect)
print("睡眠時數影響:", sleep_effect)
print("螢幕使用時數影響:", screen_effect)
print("出席率影響:", attendance_effect)
print("未加隨機誤差的成績:", quiz_score_raw)

基礎分數: 50
讀書時數影響: 7.5
睡眠時數影響: 14.0
螢幕使用時數影響: -4.8
出席率影響: 13.5
未加隨機誤差的成績: 80.2

執行前預測

每一項影響分別會是多少正或負的數值？最終的 quiz_score_raw 大約會是多少？

Try It

將 study_hours 改成 4.0 或把 screen_time_hours 改成 6.0，觀察最終成績如何變化。

Verification

你修改後的結果是否符合你的直覺（讀書多應該提升分數，螢幕使用多應該降低分數）？

Explain-back

用你的話解釋：這段程式是如何把每個變換的影響加總起來得到最終分數的？

# Mission 5：條件判斷與自訂函式

Knowledge Point

* def 用來定義自訂函式，後面跟函式名稱與參數。
* 函式內部可以使用 if / elif / else 做條件判斷，縮排必須一致。
* return 用來把結果傳回給呼叫處。

Markdown Cell

建立一個簡單的函式 describe_score，依照分數回傳對應的評語。

In [11]:
def describe_score(score):
    """根據分數回傳評語"""
    if score >= 80:
        return "表現良好"
    elif score >= 60:
        return "達到基本標準"
    else:
        return "需要加強"

# 測試不同分數
test_scores = [92, 75, 58, 40]
for s in test_scores:
    print(f"分數 {s} => {describe_score(s)}")

分數 92 => 表現良好
分數 75 => 達到基本標準
分數 58 => 需要加強
分數 40 => 需要加強

執行前預測

對於 92、75、58、40 四個分數，函式會分別回傳什麼評語？

Try It

修改函式內的門檻（例如把 >= 80 改成 >= 85），再測試一次，看看結果是否如你預期。

Verification

修改後的門檻是否真的改變了哪些分數的評語？

Explain-back

用你的話說明：函式的參數、條件判斷與 return 各自扮演什麼角色？

# Mission 6：匯入資料科學套件

Knowledge Point

* import 是載入外部套件（模組）的關鍵字。
* 常用別名：import numpy as np、import pandas as pd，方便以後呼叫。
* 函式：可以獨立呼叫的程式（例如 print()、np.random.default_rng()）。
* 方法：附帶在物件上的函式（例如 df.head()）。
* 屬性：物件內的資料（例如 df.shape）。
* 設定相同的亂數種子可以讓每次執行產出相同的隨機數，方便教學重現。

Markdown Cell

我們先匯入 NumPy 與 Pandas，並建立一個可重現的亂數產生器（隨機種子固定為 42）。

In [19]:
!mamba install pandas numpy
# 匯入套件並設定別名
import numpy as np
import pandas as pd

# 建立可重現的亂數產生器（種子 = 42）
random_seed = 42
rng = np.random.default_rng(random_seed)

# 產生 5 個 0~1 的隨機小數示範
sample_random = rng.random(5)
print("5 個隨機小數（種子 42）:", sample_random)

mambajs 0.21.4

Specs: xeus-python, numpy, matplotlib, pillow, ipywidgets>=8.1.6, ipyleaflet, scipy, pandas
Channels: emscripten-forge-4x, conda-forge

Solving environment...
Solving took 9.149 seconds
  Name           Version  Build                Channel
--------------------------------------------------------------------
+ pandas         3.0.6    np23py313h124dbc7_0  emscripten-forge-4x
+ python-tzdata  2026.4   pyh5ded981_0         conda-forge
- pip            26.2.1   pyh145f28c_0         conda-forge
5 個隨機小數（種子 42）: [0.77395605 0.43887844 0.85859792 0.69736803 0.09417735]

執行前預測

每次執行此格，sample_random 會是否相同？為什麼？

Try It

將 random_seed 改成另一個數字（例如 99），再次執行，觀察隨機數是否改變。

Verification

改變種子後，隨機數是否真的不同？若再改回 42，是否得到剛才的同樣序列？

Explain-back

用你的話解釋：為什麼我們需要「匯入」套件？np.random.default_rng 與 rng.random 各自是什麼？

# Mission 7：建立模擬的大學生學習資料

Knowledge Point

* 使用 pandas.DataFrame 建立表格資料，每列代表一位學生，每欄代表一個變數。
* np.random.default_rng().normal(mean, std, size) 產生常態分布隨機數。
* .clip(a_min, a_max) 將數值限制在指定範圍內。
* round(1) 表示保留一位小數；astype(int) 轉成整數。

Markdown Cell

現在我們將根據之前設定的參數，產生 60 筆模擬大學生學習資料，並放入變數 df 中。

In [21]:
# 學生總數（先前已定義）
n = student_count   # 60

# 使用相同的亂數種子，確保可重現
rng = np.random.default_rng(random_seed)

# 建立 DataFrame
df = pd.DataFrame({
    "student_id": np.arange(1, n+1),                                   # 1~60
    "department": rng.choice(departments, size=n),                     # 隨機選擇科系
    "sleep_hours": rng.normal(loc=average_sleep_hours, scale=1.1, size=n).round(1),
    "screen_time_hours": rng.normal(loc=5.0, scale=1.5, size=n).clip(1, 10).round(1),
    "study_hours":   rng.normal(loc=2.5, scale=1.0, size=n).clip(0.5, 6).round(1),
    "attendance_rate": rng.normal(loc=88, scale=8, size=n).clip(60, 100).astype(int)
})

# 顯示前五筆資料
df.head()

,student_id,department,sleep_hours,screen_time_hours,study_hours,attendance_rate
0,1,資訊管理,9.1,6.0,2.3,95
1,2,金融管理,6.3,4.9,1.5,77
2,3,企業管理,6.1,4.4,0.8,88
3,4,企業管理,5.8,4.9,2.0,84
4,5,企業管理,7.4,2.5,2.4,85

執行前預測

df.head() 會顯示哪些欄位？每欄的值大概會落在什麼範圍？

Try It

將 average_sleep_hours 改成 7.5，重新執行此格（請先重新執行 Mission 6 的隨機種子設定或直接在本格中重新定義 rng），觀察 sleep_hours 欄位的平均值是否變大。

Verification

欄位名稱是否完全符合規格？資料筆數是否為 60？數值是否都落在我們設定的上下限內？

Explain-back

用你的話說明：這段程式是如何從隨機數產生器得到每位學生的睡眠時數、螢幕使用時數等變數的？

# Mission 8：建立小考成績欄位

Knowledge Point

* 可以直接對 DataFrame 欄位進行向量化運算（例如 df["study_hours"] * 3）。
* np.random.default_rng().normal(0, 5, size=n) 產生平均 0、標準差 5 的隨機誤差。
* .clip(0, 100) 將成績限制在 0~100 分之間。
* .round().astype(int) 四捨五入成整數。

Markdown Cell

根據之前的公式，為每位學生計算 quiz_score（小考成績），並加入隨機誤差。

In [24]:
# 取得各欄位的 NumPy 陣列（方便向量運算）
study   = df["study_hours"].to_numpy()
sleep   = df["sleep_hours"].to_numpy()
screen  = df["screen_time_hours"].to_numpy()
attend  = df["attendance_rate"].to_numpy()

# 各項影響（依照公式分開計算）
base = 50
study_effect   = 3 * study
sleep_effect   = 2 * sleep
screen_effect  = -1.2 * screen
attend_effect  = 0.15 * attend

# 隨機誤差（平均 0，標準差 5）
rng = np.random.default_rng(random_seed)   # 保持種子一致
error = rng.normal(loc=0.0, scale=5.0, size=n)

# 原始成績（未限制）
quiz_raw = base + study_effect + sleep_effect + screen_effect + attend_effect + error

# 限制在 0~100，四捨五入成整數
df["quiz_score"] = quiz_raw.clip(0, 100).round().astype(int)

# 檢查前五筆資料（含我們關心的欄位）
df[["student_id","study_hours","sleep_hours","screen_time_hours","attendance_rate","quiz_score"]].head()

,student_id,study_hours,sleep_hours,screen_time_hours,attendance_rate,quiz_score
0,1,2.3,9.1,6.0,95,84
1,2,1.5,6.3,4.9,77,68
2,3,0.8,6.1,4.4,88,76
3,4,2.0,5.8,4.9,84,79
4,5,2.4,7.4,2.5,85,72

執行前預測

你猜第一位學生的 quiz_score 大約會是多少？（範圍 0~100）

Try It

將隨機誤差的標準差從 5 改成 2，觀察成績的變異是否變小。

Verification

所有 quiz_score 是否都在 0 到 100 之間？是否為整數？

Explain-back

用你的話說明：這段程式是如何把每個變數的影響、基礎分數與隨機誤差結合，最後限制分數範圍的？

# Mission 9：加入缺失值與異常值

Knowledge Point

* .loc[row_indexer, col_indexer] 可以根據列與欄位的標籤直接賦值。
* np.nan 代表「Not a Number」，是 Pandas 中標準的缺失值表示法。
* DataFrame 的列索引從 0 開始，因此第 5 列實際對應 student_id = 6。

Markdown Cell

我們故意在資料中製造兩筆睡眠時數的缺失值（索引 5 與 17）以及一筆異常的螢幕使用時間（索引 8，設為 15 小時），以便後續練習發現資料品質問題。

In [27]:
# 加入兩筆睡眠時數的缺失值
df.loc[[5, 17], "sleep_hours"] = np.nan

# 加入一筆異常的螢幕使用時間（15 小時，超過正常上限 10）
df.loc[8, "screen_time_hours"] = 15.0

# 檢查受影響的列
df.loc[[5, 8, 17], ["student_id","sleep_hours","screen_time_hours"]]

    student_id  sleep_hours  screen_time_hours
5            6          NaN                2.8
8            9          5.8               15.0
17          18          NaN                4.5

執行前預測

索引 5、8、17 對應的 student_id 分別是多少？你預期會看到什麼值？（例如 sleep_hours 為空、screen_time_hours 為 15）

Try It

將異常值改成 20.0，再次執行，觀察該列的螢幕使用時間是否真的變成 20。

Verification

df.loc[[5, 17], "sleep_hours"] 是否顯示為 NaN？df.loc[8, "screen_time_hours"] 是否等於你設定的異常值？

Explain-back

用你的話說明：.loc 是如何根據列號與欄位名稱精準地修改特定儲存格的值的？

# Mission 10：第一次資料品質檢查

Knowledge Point

* .head()：預覽前幾列。
* .shape：回傳 (列數, 欄數)。
* .columns：列出所有欄位名稱。
* .dtypes：顯示每欄的資料型態。
* .isna().sum()：計算每欄缺失值的數量。
* .describe()：給出數值欄位的基本統計（count、mean、std、min、25%、50%、75%、max）。

Markdown Cell

我們將依序使用上面六個常用檢查方法，觀察資料的大小、型態、缺失值以及可能的異常值。

In [28]:
# 1️⃣ 預覽前五列
print("=== df.head() ===")
df.head()

# 2️⃣ 資料形狀
print("\n=== df.shape ===")
print(df.shape)

# 3️⃣ 欄位名稱
print("\n=== df.columns ===")
print(df.columns)

# 4️⃣ 每欄型態
print("\n=== df.dtypes ===")
print(df.dtypes)

# 5️⃣ 缺失值統計
print("\n=== df.isna().sum() ===")
print(df.isna().sum())

# 6️⃣ 敘述統計
print("\n=== df.describe() ===")
print(df.describe())

=== df.head() ===

=== df.shape ===
(60, 7)

=== df.columns ===
Index(['student_id', 'department', 'sleep_hours', 'screen_time_hours',
       'study_hours', 'attendance_rate', 'quiz_score'],
      dtype='str')

=== df.dtypes ===
student_id             int32
department               str
sleep_hours          float64
screen_time_hours    float64
study_hours          float64
attendance_rate        int32
quiz_score             int32
dtype: object

=== df.isna().sum() ===
student_id           0
department           0
sleep_hours          2
screen_time_hours    0
study_hours          0
attendance_rate      0
quiz_score           0
dtype: int64

=== df.describe() ===
       student_id  sleep_hours  screen_time_hours  study_hours  \
count   60.000000    58.000000          60.000000    60.000000
mean    30.500000     6.682759           4.946667     2.473333
std     17.464249     0.822307           1.985239     0.965659
min      1.000000     4.800000           1.800000     0.500000
25%     15.750000     6.200000           3.600000     1.700000
50%     30.500000     6.750000           4.700000     2.400000
75%     45.250000     7.300000           5.625000     2.950000
max     60.000000     9.100000          15.000000     4.600000

       attendance_rate  quiz_score
count        60.000000   60.000000
mean         86.750000   78.416667
std           7.377531    5.330729
min          70.000000   68.000000
25%          82.000000   74.000000
50%          86.000000   79.000000
75%          90.250000   83.000000
max         100.000000   90.000000

執行前預測

你猜 df.shape 會是 (60, ?)？哪個欄位會顯示缺失值？異常值可能出現在哪個欄位的最大值？

Try It

移除你剛才加入的缺失值（例如 df.loc[[5,17], "sleep_hours"] = df["sleep_hours"].mean()），再次執行此格，觀察缺失值計數是否變成 0。

Verification

資料共有多少列、多少欄？
哪個欄位有缺失值？缺失值有幾筆？
從 .describe() 中，你能看到哪個欄位的 max 值異常大（例如螢幕使用時間的 max 應該遠大於 10）？
Explain-back

用你的話解釋：每一個檢查方法（.shape、.dtypes、.isna().sum()、.describe()）分別提供了什麼資訊，為什麼我們需要這些檢查？

# Mission 11：篩選與比較資料

Knowledge Point

* 單欄選取：df["column_name"] 回傳 Series。
* 多欄選取：df[["col1","col2"]] 回傳新 DataFrame。
* 布林條件：例如 df["quiz_score"] >= 80 會產生一個 True/False 系列，可用來篩選列。
* 為了易於閱讀，先把條件儲存變數再用來索引。

Markdown Cell

我們示範如何：選取單一欄位、多個欄位、找出缺失值、找出螢幕使用時間超過 10 小時的學生，以及找出成績 80 分以上的學生。

In [30]:
# 1️⃣ 單一欄位（例如 quiz_score）
print("=== 單一欄位 quiz_score 前五筆 ===")
print(df["quiz_score"].head())

# 2️⃣ 多個欄位
print("\n=== 多個欄位前五筆 ===")
print(df[["student_id","quiz_score"]].head())

# 3️⃣ 找出有缺失值的資料（以 sleep_hours 為例）
missing_sleep = df["sleep_hours"].isna()
print("\n=== 有缺失值的 sleep_hours 列索引 ===")
print(df[missing_sleep][["student_id","sleep_hours"]])

# 4️⃣ 螢幕使用時間 > 10 小時
high_screen = df["screen_time_hours"] > 10
print("\n=== 螢幕使用時間 > 10 小時的學生 ===")
print(df[high_screen][["student_id","screen_time_hours"]])

# 5️⃣ 成績 80 分以上
high_score = df["quiz_score"] >= 80
print("\n=== 成績 80 分以上的學生 ===")
print(df[high_score][["student_id","quiz_score"]].head())

=== 單一欄位 quiz_score 前五筆 ===
0    84
1    68
2    76
3    79
4    72
Name: quiz_score, dtype: int32

=== 多個欄位前五筆 ===
   student_id  quiz_score
0           1          84
1           2          68
2           3          76
3           4          79
4           5          72

=== 有缺失值的 sleep_hours 列索引 ===
    student_id  sleep_hours
5            6          NaN
17          18          NaN

=== 螢幕使用時間 > 10 小時的學生 ===
   student_id  screen_time_hours
8           9               15.0

=== 成績 80 分以上的學生 ===
    student_id  quiz_score
0            1          84
5            6          83
6            7          82
7            8          81
10          11          82

執行前預測

你預期會找到多少筆缺失值的睡眠時數？有多少學生的螢幕使用時間超過 10 小時？成績 80 分以上的學生大約會有多少人？

Try It

把成績門檻改成 >= 90，再次執行，觀察符合條件的學生數量是否減少。

Verification

單欄與多欄選取的輸出型別是否如預期（Series vs DataFrame）？
布林條件篩選後，結果列數是否符合你的預測？
Explain-back

用你的話說明：布林條件（例如 df["quiz_score"] >= 80）是如何產生 True/False 系列，然後如何用這個系列來篩選出符合條件的列的？

# Mission 12：儲存 CSV 檔案

Knowledge Point

* CSV（逗號分隔值）是一種純文字表格格式，易於在不同軟體間交換。
* DataFrame.to_csv(path, index=False, encoding="utf-8-sig")：
* index=False 意味著不把 DataFrame 的列索引寫入檔案（避免多出一欄編號）。
* encoding="utf-8-sig" 可讓 Excel 正確顯示中文（加入 BOM 標頭）。
* 在 Google Colab 中，可用 from google.colab import files; files.download(filename) 下載檔案；此程式只在 Colab 環境有效。

Markdown Cell

現在我們將整理好的資料寫成 CSV 檔案，檔名為 student_learning_data.csv，並說明如何在本機或 Colab 下載。

In [31]:
# 檔案名稱
file_name = "student_learning_data.csv"

# 寫入 CSV（不寫入索引，使用 utf-8-sig 以正確顯示中文）
df.to_csv(
    file_name,
    index=False,
    encoding="utf-8-sig"
)

print("資料已儲存為：", file_name)

資料已儲存為： student_learning_data.csv

執行前預測

執行後，你期待在目前的 Notebook 工作目錄中看到什麼檔案？檔案大概會有多少列（不含標題）？

Try It

將 encoding 改回 "utf-8"（不加 -sig），在本地用 Excel 開啟時觀察中文是否出現亂碼；若在 Colab 中，通常仍可正常顯示，但此練習只是說明編碼的影響。

Verification

檔案是否真的出現在左側檔案列表中？開啟檔案前幾行，是否可以看到標題列與我們之前的資料相符？

Explain-back

用你的話說明：to_csv 的參數 index=False 與 encoding="utf-8-sig" 各自是什麼作用？為什麼我們選擇這兩個選項？

# 最終整合任務

以下是一個 可從頭到尾直接執行 的完整程式，涵蓋所有前面 Missions 的步驟：匯入套件、設定亂數種子、建立模擬資料、加入 quiz_score、故意加入缺失值與異常值、顯示前五筆、做基本資料檢查、匯出 CSV。

* 執行前請確認：如果你在 Google Colab 中執行，最後兩行的下載程式才會起作用；在本機 Jupyter 中，檔案會直接寫到目前工作目錄，無需下載指令。

In [32]:
# ==============================
# 最終整合任務：從匯入到匯出 CSV
# ==============================

# 1️⃣ 套件匯入
import numpy as np
import pandas as pd

# 2️⃣ 基本參數（與前面任務一致）
student_count = 60
average_sleep_hours = 6.7
course_name = "Python與資料科學"
has_missing_value = True   # 此變數未在後續直接使用，僅作為示例

# 3️⃣ 可重現的亂數種子
random_seed = 42
rng = np.random.default_rng(random_seed)

# 4️⃣ 科系串列（用於隨機抽樣）
departments = ["資訊管理", "企業管理", "金融管理"]

# 5️⃣ 建立模擬資料 DataFrame
n = student_count
df = pd.DataFrame({
    "student_id": np.arange(1, n+1),
    "department": rng.choice(departments, size=n),
    "sleep_hours":   rng.normal(loc=average_sleep_hours, scale=1.1, size=n).round(1),
    "screen_time_hours": rng.normal(loc=5.0, scale=1.5, size=n).clip(1, 10).round(1),
    "study_hours":   rng.normal(loc=2.5, scale=1.0, size=n).clip(0.5, 6).round(1),
    "attendance_rate": rng.normal(loc=88, scale=8, size=n).clip(60, 100).astype(int)
})

# 6️⃣ 計算 quiz_score（依照公式，含隨機誤差）
study   = df["study_hours"].to_numpy()
sleep   = df["sleep_hours"].to_numpy()
screen  = df["screen_time_hours"].to_numpy()
attend  = df["attendance_rate"].to_numpy()

base = 50
study_effect   = 3 * study
sleep_effect   = 2 * sleep
screen_effect  = -1.2 * screen
attend_effect  = 0.15 * attend

error = rng.normal(loc=0.0, scale=5.0, size=n)   # 平均 0，標準差 5
quiz_raw = base + study_effect + sleep_effect + screen_effect + attend_effect + error

df["quiz_score"] = quiz_raw.clip(0, 100).round().astype(int)

# 7️⃣ 故意加入缺失值與異常值（與前面任務相同）
df.loc[[5, 17], "sleep_hours"] = np.nan
df.loc[8, "screen_time_hours"] = 15.0

# 8️⃣ 檢查前五筆資料（含我們關心的欄位）
print("=== 前五筆資料 ===")
df[["student_id","study_hours","sleep_hours","screen_time_hours","attendance_rate","quiz_score"]].head()

# 9️⃣ 基本資料品質檢查
print("\n=== 資料形狀 (shape) ===")
print(df.shape)

print("\n=== 欄位型態 (dtypes) ===")
print(df.dtypes)

print("\n=== 缺失值數量 (isna().sum()) ===")
print(df.isna().sum())

print("\n=== 敘述統計 (describe) ===")
print(df.describe())

# 🔟 匯出 CSV 檔案
file_name = "student_learning_data.csv"
df.to_csv(
    file_name,
    index=False,
    encoding="utf-8-sig"
)
print(f"\n資料已儲存為：{file_name}")

# 只有在 Google Colab 才會觸發下載
try:
    from google.colab import files
    files.download(file_name)
    print("（Colab 環境）檔案已觸發下載。")
except Exception:
    # 非 Colab 環境，不做任何事
    pass

=== 前五筆資料 ===

=== 資料形狀 (shape) ===
(60, 7)

=== 欄位型態 (dtypes) ===
student_id             int32
department               str
sleep_hours          float64
screen_time_hours    float64
study_hours          float64
attendance_rate        int32
quiz_score             int32
dtype: object

=== 缺失值數量 (isna().sum()) ===
student_id           0
department           0
sleep_hours          2
screen_time_hours    0
study_hours          0
attendance_rate      0
quiz_score           0
dtype: int64

=== 敘述統計 (describe) ===
       student_id  sleep_hours  screen_time_hours  study_hours  \
count   60.000000    58.000000          60.000000    60.000000
mean    30.500000     6.682759           4.946667     2.473333
std     17.464249     0.822307           1.985239     0.965659
min      1.000000     4.800000           1.800000     0.500000
25%     15.750000     6.200000           3.600000     1.700000
50%     30.500000     6.750000           4.700000     2.400000
75%     45.250000     7.300000           5.625000     2.950000
max     60.000000     9.100000          15.000000     4.600000

       attendance_rate  quiz_score
count        60.000000   60.000000
mean         86.750000   78.733333
std           7.377531    6.627796
min          70.000000   63.000000
25%          82.000000   75.000000
50%          86.000000   80.000000
75%          90.250000   82.250000
max         100.000000   92.000000

資料已儲存為：student_learning_data.csv

執行完成後，你應該會看到：

* 前五筆資料的表格印出。
* 資料形狀為 (60, 8)（包括 student_id 到 quiz_score 共 8 欄）。
* sleep_hours 欄位顯示 2 筆缺失值。
* screen_time_hours 欄位的最大值遠大於 10（因為我們故意設了 15）。
* 工作目錄中出現 student_learning_data.csv 檔案。
* 若在 Colab，瀏覽器會自動下載該 CSV。

### 最終學習檢核
請用你自己的話回答以下問題（不使用選擇題，盡量寫出完整句子）。

變數與資料值有什麼不同？

例如：變數是給資料取的名字，資料值則是實際儲存在記憶體裡的內容（如數字或文字）。

串列與字典有什麼不同？

例如：串列是有順序的集合，透過編號（索引）取值；字典則是無順序的「鍵：值」配對，透過鍵名取值。

函式與方法有什麼不同？

例如：函式是可以獨立呼叫的程式塊（如 print()），方法是附帶在特定物件上的函式（如 df.head()），必須透過該物件來呼叫。

為什麼程式能執行不代表分析結果一定正確？

例如：程式可能沒有語法錯誤，但如果邏輯錯誤（比如公式寫錯、使用了錯誤的欄位），得到的結果仍會是錯誤的。

為什麼模擬資料中的相關關係不能直接解釋為真實因果關係？

例如：我們是人為設計的數學公式產生資料，其中的「關係」只是我們設定的規律，並不代表真實世界中讀書時數真的會直接造成成績提升；其他未控制的因素可能同時影響兩個變數。

### Explain‑back 任務
請選擇三行你原本看不懂的程式碼（可以是任何 Missions 中的程式），分別說明：

輸入：這行程式到底在使用哪些變數或值作為輸入？
處理：程式對這些輸入做了什麼運算或函式呼叫？
輸出：執行後會產生什麼結果（例如印出文字、改變變數、產生新的欄位等）？
驗證：你是如何透過修改數值、觀察印出結果或使用除錯方式來確認這行程式真的如你所理解地運作的？
例如，你可以選擇：

df.loc[[5, 17], "sleep_hours"] = np.nan
quiz_raw = base + study_effect + sleep_effect + screen_effect + attend_effect + error
df.to_csv(file_name, index=False, encoding="utf-8-sig")
依照上面四個步驟，寫出你的說明。